version: '3.8'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  bank-account-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-account-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/bankdb?authSource=admin
      JWT_SECRET: HSHYYEGSJKLSOJE
    depends_on:
      - mongodb

volumes:
  mongo_data:
    driver: local
